import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import sharp from 'sharp';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const generateImage = async (comicSpec, outputPath) => {
  console.error(`Generating image for ${comicSpec.category}...`);
  console.error(`Prompt: ${comicSpec.comic.image_prompt.substring(0, 100)}...`);
  
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    throw new Error('OPENROUTER_API_KEY environment variable not set');
  }
  
  const baseUrl = process.env.OPENROUTER_BASE_URL || 'https://llmfoundry.straivedemo.com/openrouter/v1';
  const model = process.env.OPENROUTER_MODEL || 'google/gemini-3-pro-image-preview';
  

  console.error(`Using API: ${baseUrl}`);
  console.error(`Model: ${model}`);
  
  const systemPrompt = `You are a professional editorial cartoonist specializing in RK Laxman style cartoons and Amul advertisement aesthetics. 
Generate images with:
- Simple black ink line art with minimal color accents
- Bold, expressive characters in classic Indian editorial style
- Clean, uncluttered composition
- Witty visual storytelling
- Family-friendly content`;

  const fullPrompt = `${systemPrompt}

Image Generation Request:
${comicSpec.comic.image_prompt}

Caption to incorporate: "${comicSpec.comic.caption}"

Style Requirements:
- Simple black ink line art
- Minimal color (like Amul ads)
- Bold, expressive characters
- Clean composition
- Indian editorial cartoon aesthetic

Strictly Avoid: ${comicSpec.comic.negative_prompt}

Generate and must return a complete image that can be used directly as an editorial cartoon.`;

  const response = await fetch(`${baseUrl}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
      'HTTP-Referer': 'https://github.com/comicgen',
      'X-Title': 'Daily News Comic Bot'
    },
    body: JSON.stringify({
      model,
      messages: [
        {
          role: 'user',
          content: fullPrompt
        }
      ]
    })
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error(`API Error Details:`, {
      status: response.status,
      statusText: response.statusText,
      response: errorText.substring(0, 500)
    });
    throw new Error(`API request failed (${response.status} ${response.statusText}): ${errorText.substring(0, 200)}`);
  }

  const data = await response.json();
  const message = data.choices?.[0]?.message;
  
  if (!message) {
    throw new Error('No message received from API');
  }

  // Extract image URL from response
  let imageUrl = null;
  
  if (message.images?.[0]?.image_url?.url) {
    imageUrl = message.images[0].image_url.url;
  } else if (message.content?.includes('data:image')) {
    imageUrl = message.content;
  } else if (message.content) {
    // Save text response for debugging
    fs.writeFileSync(outputPath.replace('.webp', '.txt'), message.content);
    console.error(`Text response saved to ${outputPath.replace('.webp', '.txt')}`);
  }

  if (imageUrl) {
    // Save image data
    let imageBuffer;
    
    if (imageUrl.startsWith('data:image')) {
      // Base64 image
      const base64Data = imageUrl.split(',')[1];
      imageBuffer = Buffer.from(base64Data, 'base64');
    } else if (imageUrl.startsWith('http')) {
      // URL - download the image
      const imageResponse = await fetch(imageUrl);
      if (!imageResponse.ok) {
        throw new Error(`Failed to download image: ${imageResponse.status}`);
      }
      const arrayBuffer = await imageResponse.arrayBuffer();
      imageBuffer = Buffer.from(arrayBuffer);
    }
    
    // Convert to webp with compression
    if (imageBuffer) {
      await sharp(imageBuffer)
        .webp({ 
          quality: 80,        // Compression quality (0-100)
          effort: 6,          // Compression effort (0-6, higher is better compression)
          lossless: false     // Use lossy compression for smaller file size
        })
        .toFile(outputPath);
      
      const stats = fs.statSync(outputPath);
      const fileSizeKB = (stats.size / 1024).toFixed(2);
      console.error(`✓ Image saved to ${outputPath} (${fileSizeKB} KB)`);
    }
  } else {
    throw new Error('No image generated by API');
  }
};

/**
 * Process a daily JSON file and generate all images
 */
const processDay = async (dateStr) => {
  const dataPath = path.join(__dirname, '..', 'data', `${dateStr}.json`);
  const imagesDir = path.join(__dirname, '..', 'images');
  
  // Ensure images directory exists
  if (!fs.existsSync(imagesDir)) {
    fs.mkdirSync(imagesDir, { recursive: true });
  }
  
  // Read comic specs
  if (!fs.existsSync(dataPath)) {
    throw new Error(`No data file found for ${dateStr}`);
  }
  
  // Read file and handle encoding issues
  const buffer = fs.readFileSync(dataPath);
  let content;
  
  // Check for BOMs and decode accordingly
  if (buffer[0] === 0xFF && buffer[1] === 0xFE) {
    // UTF-16 LE BOM
    content = buffer.toString('utf16le').replace(/^\uFEFF/, '');
  } else if (buffer[0] === 0xEF && buffer[1] === 0xBB && buffer[2] === 0xBF) {
    // UTF-8 BOM
    content = buffer.toString('utf8').replace(/^\uFEFF/, '');
  } else {
    // No BOM or unknown encoding
    content = buffer.toString('utf8').replace(/^\uFEFF/, '');
  }
  
  const data = JSON.parse(content);
  
  console.error(`\n📰 Processing ${data.items.length} comics for ${dateStr}...\n`);
  
  // Generate images for each comic sequentially
  const results = [];
  const categoryCounters = {}; // Track count per category
  
  for (const item of data.items) {
    // Increment counter for this category
    if (!categoryCounters[item.category]) {
      categoryCounters[item.category] = 0;
    }
    categoryCounters[item.category]++;
    
    // Create unique filename with index
    const imagePath = path.join(imagesDir, `${dateStr}_${item.category}_${categoryCounters[item.category]}.webp`);
    
    try {
      await generateImage(item, imagePath);
      results.push({ category: item.category, status: 'success', path: imagePath });
    } catch (error) {
      console.error(`✗ Failed to generate ${item.category} #${categoryCounters[item.category]}: ${error.message}`);
      results.push({ category: item.category, status: 'failed', error: error.message });
      throw error; // Re-throw to fail the process
    }
  }
  
  console.error(`\n✓ Completed image generation for ${dateStr}`);
  return results;
};

/**
 * Main execution
 */
const main = async () => {
  const targetDate = process.argv[2] || new Date().toISOString().split('T')[0];
  
  console.error(`🎨 Daily News Comic Image Generator`);
  console.error(`Target Date: ${targetDate}\n`);
  
  const results = await processDay(targetDate);
  
  // Summary
  const successful = results.filter(r => r.status === 'success').length;
  const failed = results.filter(r => r.status === 'failed').length;
  
  console.error(`\n📊 Summary: ${successful} successful, ${failed} failed`);
  
  if (failed > 0) {
    process.exit(1);
  }
};

// Run main function
main().catch(err => {
  console.error('\n❌ Error:', err.message);
  process.exit(1);
});

export { generateImage, processDay };
